Traceback (most recent call last):
  File "/home/runner/work/cov_pred_finance/cov_pred_finance/.venv/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/work/cov_pred_finance/cov_pred_finance/.venv/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/work/cov_pred_finance/cov_pred_finance/.venv/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/runner/work/cov_pred_finance/cov_pred_finance/.venv/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/runner/work/cov_pred_finance/cov_pred_finance/.venv/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/work/cov_pred_finance/cov_pred_finance/.venv/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Pairs of halflife volatility vs halflife covariances
pairs = [(10, 10), (21, 21), (21, 63)]

combinations = from_ewmas(
    returns,
    pairs,
    clip_at=4.2,
    mean=True
)

weights = pd.DataFrame({result.time : result.weights for result in combinations.solve(window=10)}).transpose()
weights
------------------

----- stdout -----
Solver did not converge at time 2017-12-20 00:00:00
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[5], line 11[0m
[1;32m      2[0m pairs [38;5;241m=[39m [([38;5;241m10[39m, [38;5;241m10[39m), ([38;5;241m21[39m, [38;5;241m21[39m), ([38;5;241m21[39m, [38;5;241m63[39m)]
[1;32m      4[0m combinations [38;5;241m=[39m from_ewmas(
[1;32m      5[0m     returns,
[1;32m      6[0m     pairs,
[1;32m      7[0m     clip_at[38;5;241m=[39m[38;5;241m4.2[39m,
[1;32m      8[0m     mean[38;5;241m=[39m[38;5;28;01mTrue[39;00m
[1;32m      9[0m )
[0;32m---> 11[0m weights [38;5;241m=[39m pd[38;5;241m.[39mDataFrame({result[38;5;241m.[39mtime : result[38;5;241m.[39mweights [38;5;28;01mfor[39;00m result [38;5;129;01min[39;00m combinations[38;5;241m.[39msolve(window[38;5;241m=[39m[38;5;241m10[39m)})[38;5;241m.[39mtranspose()
[1;32m     12[0m weights

Cell [0;32mIn[5], line 11[0m, in [0;36m<dictcomp>[0;34m(.0)[0m
[1;32m      2[0m pairs [38;5;241m=[39m [([38;5;241m10[39m, [38;5;241m10[39m), ([38;5;241m21[39m, [38;5;241m21[39m), ([38;5;241m21[39m, [38;5;241m63[39m)]
[1;32m      4[0m combinations [38;5;241m=[39m from_ewmas(
[1;32m      5[0m     returns,
[1;32m      6[0m     pairs,
[1;32m      7[0m     clip_at[38;5;241m=[39m[38;5;241m4.2[39m,
[1;32m      8[0m     mean[38;5;241m=[39m[38;5;28;01mTrue[39;00m
[1;32m      9[0m )
[0;32m---> 11[0m weights [38;5;241m=[39m pd[38;5;241m.[39mDataFrame({[43mresult[49m[38;5;241;43m.[39;49m[43mtime[49m : result[38;5;241m.[39mweights [38;5;28;01mfor[39;00m result [38;5;129;01min[39;00m combinations[38;5;241m.[39msolve(window[38;5;241m=[39m[38;5;241m10[39m)})[38;5;241m.[39mtranspose()
[1;32m     12[0m weights

[0;31mAttributeError[0m: 'NoneType' object has no attribute 'time'

